# Generated by Django 4.1.1 on 2023-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Nonmetal', 'Nonmetal'), ('Noble gas', 'Noble gas')], max_length=9, verbose_name='Metal / Nonmetal '),
        ),
    ]
