# Generated by Django 4.1.1 on 2023-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='family',
            field=models.CharField(choices=[('Alkali', 'Alkali'), ('Alkaline Earth', 'Alkaline Earth'), ('Transition Metal', 'Transition Metal'), ('Post-transition Metal', 'Post-transition Metal'), ('Metalloid', 'Metalloid'), ('Other Nonmetals', 'Other Nonmetals'), ('Halogen', 'Halogen'), ('Noble Gas', 'Noble Gas'), ('Lanthanide', 'Lanthanide'), ('Actinide', 'Actinide')], max_length=21, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Nonmetal', 'Nonmetal'), ('Noble Gas', 'Noble Gas')], max_length=9, verbose_name='Metal / Nonmetal / Noble Gas'),
        ),
    ]
