# Generated by Django 4.1.1 on 2023-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_element_family_alter_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='covalentsubstance',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='covalentsubstance',
            name='trivial_names',
            field=models.TextField(blank=True, default='', verbose_name='Trivial names'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='trivial_names',
            field=models.TextField(blank=True, default='', verbose_name='Trivial names'),
        ),
    ]
