# Generated by Django 4.1.1 on 2023-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_covalentsubstance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covalentsubstance',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='covalentsubstance',
            name='trivial_names',
            field=models.TextField(blank=True, verbose_name='Trivial names'),
        ),
        migrations.AlterField(
            model_name='ionicsubstance',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ionicsubstance',
            name='trivial_names',
            field=models.TextField(blank=True, verbose_name='Trivial names'),
        ),
    ]
