# Generated by Django 4.1.1 on 2023-06-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_covalentsubstance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='covalentsubstance',
            name='color',
            field=models.CharField(default='Transparent', max_length=16, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='covalentsubstance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='covalentsubstance',
            name='is_organic',
            field=models.BooleanField(default=False, verbose_name='Is Organic'),
        ),
        migrations.AddField(
            model_name='covalentsubstance',
            name='smell',
            field=models.CharField(default='Without', max_length=16, verbose_name='Smell'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='color',
            field=models.CharField(default='Transparent', max_length=16, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='is_organic',
            field=models.BooleanField(default=False, verbose_name='Is Organic'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='smell',
            field=models.CharField(default='Without', max_length=16, verbose_name='Smell'),
        ),
        migrations.AlterField(
            model_name='covalentsubstance',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ionicsubstance',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.RenameModel(
            old_name='Equation',
            new_name='Reaction',
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('reacts_with', models.ManyToManyField(to='api.klass', verbose_name='Reacts With')),
                ('unique_reactions', models.ManyToManyField(to='api.reaction', verbose_name='Unique Reactions')),
            ],
        ),
        migrations.AddField(
            model_name='covalentsubstance',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.klass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.klass', verbose_name='Class'),
        ),
    ]
