# Generated by Django 4.1.1 on 2023-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_covalentsubstance_is_organic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covalentsubstance',
            name='is_organic',
        ),
        migrations.RemoveField(
            model_name='ionicsubstance',
            name='is_organic',
        ),
        migrations.AddField(
            model_name='klass',
            name='is_organic',
            field=models.BooleanField(default=False, verbose_name='Is Organic'),
        ),
    ]
