# Generated by Django 4.1.1 on 2023-06-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_covalentsubstance_is_organic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubKlass',
            fields=[
                ('klass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.klass')),
            ],
            bases=('api.klass',),
        ),
        migrations.AlterField(
            model_name='klass',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='reacts_with',
            field=models.ManyToManyField(blank=True, to='api.klass', verbose_name='Reacts With'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='unique_reactions',
            field=models.ManyToManyField(blank=True, to='api.reaction', verbose_name='Unique Reactions'),
        ),
    ]
