# Generated by Django 4.1.1 on 2023-06-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subklass_alter_klass_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubKlass',
        ),
    ]
