# Generated by Django 4.2.2 on 2023-06-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_subklass'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='configuration',
            field=models.CharField(default='', max_length=128, verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Nonmetal', 'Nonmetal'), ('Noble Gas', 'Noble Gas')], max_length=9, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='is_organic',
            field=models.BooleanField(default=True, verbose_name='Is Organic'),
        ),
    ]
