# Generated by Django 4.2.2 on 2023-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_element_configuration_alter_element_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='configuration',
            field=models.CharField(max_length=128, verbose_name='Configuration'),
        ),
    ]
