# Generated by Django 4.1.1 on 2023-07-27 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_element_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='oxidations',
            field=models.CharField(max_length=32, validators=[django.core.validators.int_list_validator], verbose_name='Oxidations'),
        ),
    ]
