# Generated by Django 4.1.1 on 2023-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_element_oxidations'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='article',
            field=models.TextField(default='', verbose_name='Article'),
        ),
    ]
