# Generated by Django 4.1.1 on 2023-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_klass_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='article',
            field=models.TextField(blank=True, verbose_name='Article'),
        ),
    ]
