# Generated by Django 4.1.1 on 2023-08-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_complexion_covalentsubstance_ionicsubstance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='description',
        ),
    ]
