# Generated by Django 4.1.1 on 2023-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_klass_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexion',
            options={'verbose_name': 'complex ion', 'verbose_name_plural': 'complex ions'},
        ),
        migrations.AlterModelOptions(
            name='covalentsubstance',
            options={'verbose_name': 'covalent substance', 'verbose_name_plural': 'covalent substances'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'element', 'verbose_name_plural': 'elements'},
        ),
        migrations.AlterModelOptions(
            name='ionicsubstance',
            options={'verbose_name': 'ionic substance', 'verbose_name_plural': 'ionic substances'},
        ),
        migrations.AlterModelOptions(
            name='klass',
            options={'verbose_name': 'klass', 'verbose_name_plural': 'klasses'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'reaction', 'verbose_name_plural': 'reactions'},
        ),
        migrations.AlterModelOptions(
            name='simpleion',
            options={'verbose_name': 'simple ion', 'verbose_name_plural': 'simple ions'},
        ),
        migrations.AddField(
            model_name='element',
            name='electronegativity',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=3, verbose_name='Electronegativity'),
        ),
        migrations.AlterField(
            model_name='ionicsubstance',
            name='complex_ions',
            field=models.ManyToManyField(blank=True, to='api.complexion', verbose_name='Complex Ions'),
        ),
        migrations.AlterField(
            model_name='ionicsubstance',
            name='simple_ions',
            field=models.ManyToManyField(blank=True, to='api.simpleion', verbose_name='Simple Ions'),
        ),
    ]
