# Generated by Django 4.1.1 on 2023-08-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_complexion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='electronegativity',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Electronegativity'),
        ),
    ]
