# Generated by Django 4.1.1 on 2023-08-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_element_electronegativity'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexion',
            name='color',
            field=models.CharField(default='Transparent', max_length=16, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='complexion',
            name='name',
            field=models.CharField(blank=True, max_length=16, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='simpleion',
            name='color',
            field=models.CharField(default='Transparent', max_length=16, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='simpleion',
            name='name',
            field=models.CharField(blank=True, max_length=16, verbose_name='Name'),
        ),
    ]
