# Generated by Django 4.1.1 on 2023-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_complexion_color_complexion_name_simpleion_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covalentsubstance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ionicsubstance',
            name='description',
        ),
        migrations.AddField(
            model_name='covalentsubstance',
            name='article',
            field=models.TextField(blank=True, verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='article',
            field=models.TextField(blank=True, verbose_name='Article'),
        ),
    ]
