# Generated by Django 4.1.1 on 2023-09-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_covalentsubstance_image_element_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covalentsubstance',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='covalentsubstance',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='elementcountincovalentsubstance',
            name='element',
        ),
        migrations.RemoveField(
            model_name='elementcountincovalentsubstance',
            name='substance',
        ),
        migrations.RemoveField(
            model_name='elementcountinion',
            name='complex_ion',
        ),
        migrations.RemoveField(
            model_name='elementcountinion',
            name='element',
        ),
        migrations.RemoveField(
            model_name='ionicsubstance',
            name='complex_ions',
        ),
        migrations.RemoveField(
            model_name='ionicsubstance',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='ionicsubstance',
            name='simple_ions',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='covalent_products',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='covalent_reactives',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='ionic_products',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='ionic_reactives',
        ),
        migrations.RemoveField(
            model_name='simpleion',
            name='element',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='unique_reactions',
        ),
        migrations.AlterField(
            model_name='element',
            name='atomic_number',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Atomic Number'),
        ),
        migrations.AlterField(
            model_name='element',
            name='configuration',
            field=models.CharField(max_length=128, unique=True, verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='element',
            name='mass',
            field=models.DecimalField(decimal_places=3, max_digits=6, unique=True, verbose_name='Mass'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='ComplexIon',
        ),
        migrations.DeleteModel(
            name='CovalentSubstance',
        ),
        migrations.DeleteModel(
            name='ElementCountInCovalentSubstance',
        ),
        migrations.DeleteModel(
            name='ElementCountInIon',
        ),
        migrations.DeleteModel(
            name='IonicSubstance',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='SimpleIon',
        ),
    ]
