# Generated by Django 4.1.1 on 2023-09-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_complexion_covalentsubstance_ionicsubstance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplexIon',
            new_name='Ion',
        ),
        migrations.AlterModelOptions(
            name='ion',
            options={'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.RemoveField(
            model_name='ionicsubstance',
            name='complex_ions',
        ),
        migrations.RemoveField(
            model_name='ionicsubstance',
            name='simple_ions',
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='anion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anions', to='api.ion', verbose_name='Anion'),
        ),
        migrations.AddField(
            model_name='ionicsubstance',
            name='cation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cations', to='api.ion', verbose_name='Cation'),
        ),
        migrations.DeleteModel(
            name='SimpleIon',
        ),
    ]
