# Generated by Django 4.1.1 on 2023-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_complexion_ion_alter_ion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ion',
            name='hydroxogroups',
            field=models.CharField(default='0', max_length=1, verbose_name='Hydroxogroups'),
        ),
    ]
