# Generated by Django 4.1.1 on 2023-09-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_ion_hydroxogroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementcountincovalentsubstance',
            old_name='valency',
            new_name='oxidation',
        ),
        migrations.RenameField(
            model_name='elementcountinion',
            old_name='valency',
            new_name='oxidation',
        ),
    ]
