# Generated by Django 4.1.1 on 2023-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_complex_ion_elementcountinion_ion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ion',
            name='elements',
            field=models.ManyToManyField(related_name='elements', through='api.ElementCountInIon', to='api.element', verbose_name='Elements'),
        ),
    ]
