# Generated by Django 4.1.1 on 2023-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_elementcountincovalentsubstance_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ion',
            name='name1',
            field=models.CharField(blank=True, max_length=16, verbose_name='Name'),
        ),
    ]
