# Generated by Django 4.1.1 on 2023-09-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_ion_main_element_alter_ion_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ion',
            name='main_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_element', to='api.element', verbose_name='Main Element'),
        ),
    ]
