# Generated by Django 4.1.1 on 2023-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_ion_main_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ion',
            options={'ordering': ('main_element',), 'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.AlterField(
            model_name='ion',
            name='name1',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
    ]
