# Generated by Django 4.1.1 on 2023-09-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_ionicsubstance_soluble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ion',
            name='name1',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
    ]
