# Generated by Django 4.1.1 on 2023-09-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_covalentsubstance_aggregation_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ion',
            name='positive',
            field=models.BooleanField(default=False, verbose_name='Positive'),
        ),
    ]
