# Generated by Django 4.1.1 on 2023-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_ion_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ion',
            name='positive',
            field=models.BooleanField(verbose_name='Positive'),
        ),
    ]
