# Generated by Django 4.1.1 on 2023-09-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_ion_positive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ion',
            options={'ordering': ('positive', 'main_element'), 'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.AlterField(
            model_name='ionicsubstance',
            name='anion',
            field=models.ForeignKey(limit_choices_to={'positive': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anions', to='api.ion', verbose_name='Anion'),
        ),
        migrations.AlterField(
            model_name='ionicsubstance',
            name='cation',
            field=models.ForeignKey(limit_choices_to={'positive': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cations', to='api.ion', verbose_name='Cation'),
        ),
    ]
