# Generated by Django 4.1.1 on 2023-10-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_ion_options_alter_ionicsubstance_anion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ion',
            name='main_element_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_element_count', to='api.elementcountinion', verbose_name='Main Element Count'),
        ),
    ]
