# Generated by Django 4.1.1 on 2023-10-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_ion_main_element_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ion',
            options={'ordering': ('positive',), 'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.RemoveField(
            model_name='ion',
            name='main_element',
        ),
        migrations.AlterField(
            model_name='ion',
            name='main_element_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_element_count', to='api.elementcountinion', verbose_name='Main Element Count'),
        ),
    ]
