# Generated by Django 4.1.1 on 2023-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_ion_options_remove_ion_main_element_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ion',
            options={'ordering': ('positive', 'main_element_count__element', 'main_element_count__oxidation'), 'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.AddField(
            model_name='element',
            name='group_int',
            field=models.SmallIntegerField(default=1, verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='period_int',
            field=models.SmallIntegerField(default=1, verbose_name='Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementcountincovalentsubstance',
            name='count_int',
            field=models.SmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='elementcountincovalentsubstance',
            name='oxidation_int',
            field=models.SmallIntegerField(default=1, verbose_name='Oxidation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementcountinion',
            name='count_int',
            field=models.SmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='elementcountinion',
            name='oxidation_int',
            field=models.SmallIntegerField(default=1, verbose_name='Oxidation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ion',
            name='oxidation_int',
            field=models.SmallIntegerField(default=1, verbose_name='Oxidation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='oxidations',
            field=models.CharField(max_length=16, verbose_name='Oxidations'),
        ),
    ]
