# Generated by Django 4.1.1 on 2023-10-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_ion_options_element_group_int_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ion',
            options={'ordering': ('positive', 'main_element_count__element', 'main_element_count__oxidation_int'), 'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.RemoveField(
            model_name='element',
            name='group',
        ),
        migrations.RemoveField(
            model_name='element',
            name='period',
        ),
        migrations.RemoveField(
            model_name='elementcountincovalentsubstance',
            name='count',
        ),
        migrations.RemoveField(
            model_name='elementcountincovalentsubstance',
            name='oxidation',
        ),
        migrations.RemoveField(
            model_name='elementcountinion',
            name='count',
        ),
        migrations.RemoveField(
            model_name='elementcountinion',
            name='oxidation',
        ),
        migrations.RemoveField(
            model_name='ion',
            name='oxidation',
        ),
    ]
