# Generated by Django 4.1.1 on 2023-10-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_ion_options_remove_element_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ion',
            options={'ordering': ('positive', 'main_element_count__element', 'main_element_count__oxidation'), 'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.RenameField(
            model_name='element',
            old_name='group_int',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='period_int',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='elementcountincovalentsubstance',
            old_name='count_int',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='elementcountincovalentsubstance',
            old_name='oxidation_int',
            new_name='oxidation',
        ),
        migrations.RenameField(
            model_name='elementcountinion',
            old_name='count_int',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='elementcountinion',
            old_name='oxidation_int',
            new_name='oxidation',
        ),
        migrations.RenameField(
            model_name='ion',
            old_name='oxidation_int',
            new_name='oxidation',
        ),
    ]
