# Generated by Django 4.1.1 on 2023-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_ion_oxidation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ion',
            options={'ordering': ('main_element_count__element', 'main_element_count__oxidation'), 'verbose_name': 'ion', 'verbose_name_plural': 'ions'},
        ),
        migrations.AlterField(
            model_name='ion',
            name='positive',
            field=models.BooleanField(default=False),
        ),
    ]
