# Generated by Django 4.1.1 on 2023-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_ion_options_alter_ion_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='suffix',
            field=models.CharField(default='', max_length=8, verbose_name='Suffix'),
        ),
    ]
